import type { ViewpointId } from '../../../app/types/perigee'

/**
 * Generated by `scripts/audio.sh`. Do not edit by hand: the filenames carry
 * the first eight hex characters of each file's SHA-256, so a changed track
 * ships under a new name and the immutable cache rule in `public/_headers`
 * stays correct.
 */
export interface AmbientTrack {
  url: string
  /** Decoded length. The runtime loops inside these ends, never across them. */
  seconds: number
  /** Size on the wire, measured at encode time and pinned by the tests. */
  bytes: number
}

export const ambientTracks = {
  'rooftop': { url: '/assets/audio/rooftop-6e2d0cd1.mp3', seconds: 114.00, bytes: 1825270 },
  'hilltop': { url: '/assets/audio/hilltop-c345fdf9.mp3', seconds: 114.00, bytes: 1825270 },
  'lakeside': { url: '/assets/audio/lakeside-782e4680.mp3', seconds: 116.00, bytes: 1857035 },
  'cabo-da-roca': { url: '/assets/audio/cabo-da-roca-7c670fe5.mp3', seconds: 114.00, bytes: 1825270 },
} as const satisfies Record<ViewpointId, AmbientTrack>
