#!/usr/bin/env bash
# Prepares the ambient music tracks and regenerates src/perigee/audio/AudioManifest.ts.
#
# Sources are not kept in the repository, following the normal-map DEM precedent:
# drop the four master files into tmp/audio-sources/ (git-ignored) as
# rooftop.mp3, hilltop.mp3, lakeside.mp3, cabo-da-roca.mp3, then run this.
#
# Requires ffmpeg (brew install ffmpeg). Idempotent: rerunning it reproduces the
# same bytes, so the content hash in each filename stays stable.
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
sources="$root/tmp/audio-sources"
out_dir="$root/public/assets/audio"
work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT

# Seconds of the tail crossfaded onto the head so the file's end joins its start.
# Long enough to hide a phrase boundary, short enough not to blur the join.
CROSSFADE=4
# Integrated loudness. The engine only scales this with the volume control, so
# the four tracks have to match each other before they reach it.
LUFS=-20
BITRATE=128

# viewpoint|start seconds|section length seconds
# Each section skips the master's intro and its outro fade, and ends on the
# fullest part of the piece so the join lands inside a sustained passage.
SECTIONS=(
  "rooftop|30|118"
  "hilltop|22|118"
  "lakeside|16|120"
  "cabo-da-roca|26|118"
)

command -v ffmpeg >/dev/null || { echo "ffmpeg not found (brew install ffmpeg)" >&2; exit 1; }
mkdir -p "$out_dir"

declare -a MANIFEST=()

for entry in "${SECTIONS[@]}"; do
  IFS='|' read -r name start length <<<"$entry"
  src="$sources/$name.mp3"
  [ -f "$src" ] || { echo "missing source: $src" >&2; exit 1; }

  # 1. Trim to the section, 2. resample, 3. match loudness across viewpoints.
  ffmpeg -v error -y -ss "$start" -t "$length" -i "$src" \
    -af "aresample=44100,loudnorm=I=$LUFS:TP=-1.5:LRA=11" \
    -ar 44100 -ac 2 -c:a pcm_s16le "$work/$name-section.wav"

  # 4. Bake the loop. The section's last CROSSFADE seconds are faded into its
  #    first CROSSFADE seconds, and that join becomes the head of the file:
  #
  #      file  = join([L-X, L) over [0, X))  +  body([X, L-X))
  #
  #    so the body's end and the join's start are the same instant (L-X), and
  #    the join's end and the body's start are the same instant (X). The file
  #    therefore runs into itself in both directions with nothing repeated.
  #    Putting the join last instead plays four seconds of the piece twice.
  tail_start=$(awk "BEGIN{print $length - $CROSSFADE}")
  ffmpeg -v error -y -i "$work/$name-section.wav" -filter_complex \
    "[0:a]atrim=0:$CROSSFADE,asetpts=PTS-STARTPTS[head]; \
     [0:a]atrim=$CROSSFADE:$tail_start,asetpts=PTS-STARTPTS[body]; \
     [0:a]atrim=$tail_start,asetpts=PTS-STARTPTS[tail]; \
     [tail][head]acrossfade=d=$CROSSFADE:c1=tri:c2=tri[join]; \
     [join][body]concat=n=2:v=0:a=1[out]" \
    -map "[out]" -c:a pcm_s16le "$work/$name-loop.wav"

  # 5. Encode. libmp3lame writes the Xing/LAME header, so browsers report the
  #    real duration; the runtime still insets the loop points, because not
  #    every decoder trims the encoder padding.
  ffmpeg -v error -y -i "$work/$name-loop.wav" \
    -c:a libmp3lame -b:a "${BITRATE}k" -ar 44100 -write_xing 1 "$work/$name.mp3"

  # 6. Name by content, so /assets/* can stay immutable for a year.
  hash="$(shasum -a 256 "$work/$name.mp3" | cut -c1-8)"
  file="$name-$hash.mp3"
  rm -f "$out_dir/$name-"*.mp3
  cp "$work/$name.mp3" "$out_dir/$file"

  seconds="$(ffprobe -v error -show_entries format=duration -of csv=p=0 "$out_dir/$file")"
  bytes="$(wc -c <"$out_dir/$file" | tr -d ' ')"
  MANIFEST+=("  '$name': { url: '/assets/audio/$file', seconds: $(printf '%.2f' "$seconds"), bytes: $bytes },")
  echo "$file  $(printf '%.1f' "$seconds")s  $(du -h "$out_dir/$file" | cut -f1)"
done

manifest="$root/src/perigee/audio/AudioManifest.ts"
{
  echo "import type { ViewpointId } from '../../../app/types/perigee'"
  echo
  echo "/**"
  echo " * Generated by \`scripts/audio.sh\`. Do not edit by hand: the filenames carry"
  echo " * the first eight hex characters of each file's SHA-256, so a changed track"
  echo " * ships under a new name and the immutable cache rule in \`public/_headers\`"
  echo " * stays correct."
  echo " */"
  echo "export interface AmbientTrack {"
  echo "  url: string"
  echo "  /** Decoded length. The runtime loops inside these ends, never across them. */"
  echo "  seconds: number"
  echo "  /** Size on the wire, measured at encode time and pinned by the tests. */"
  echo "  bytes: number"
  echo "}"
  echo
  echo "export const ambientTracks = {"
  printf '%s\n' "${MANIFEST[@]}"
  echo "} as const satisfies Record<ViewpointId, AmbientTrack>"
} > "$manifest"

echo "wrote $manifest"
